config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :questions do
    resources :answers, shallow: true
  end

  root to: 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :body, presence: true
  validates :best, presence: false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, class_name: 'Question', foreign_key: 'user_id', dependent: :destroy
  has_many :answers, class_name: 'Answer', foreign_key: 'user_id', dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def author_of?(resource)
    id == resource.user_id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_answer, only: %i[show edit update destroy]
  before_action :load_question, only: %i[index create]

  def index
    @answers = @question.answers
  end

  def show; end

  def new
    @answer = Answer.new
  end

  def edit; end

  def create
    @answer = current_user.answers.create(answer_params.merge(question: @question))
  end

  def update
    best_answer
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    @answer.destroy if current_user.author_of?(@answer)
  end

  private

  def load_question
    @question = Question.find_by!(id: params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :user_id, :best)
  end

  def best_answer
    best_answer = Answer.find_by(best: true)
    return unless best_answer

    best_answer.best = false
    best_answer.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def edit; end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    @question.destroy if current_user.author_of?(@question)
    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :user_id)
  end

  def load_question
    @question = Question.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
div.answer id="answer-#{answer.id}"

  p= "BEST!" if answer.best == true
  p= answer.best
  p= answer.body
  p= answer.user.email

  td
    -if current_user&.author_of?(answer)
      p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
      = form_with model: answer, class: 'hidden', local: false, html: { id: "edit-answer-#{answer.id }"} do |f|
        = f.label :body, 'Your answer'
        = f.text_area :body
        = f.submit 'Save answer'
        = f.check_box :best
        = f.label :best, "Best"
      td
        p= link_to 'Delete', answer, method: :delete, remote: true, html: { id: "delete-answer-#{answer.id }"}
  br

app/views/answers/create.js.erb
$(".answer-errors").html('<%= render 'shared/errors', resource: @answer %>');
<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$(".answer-errors").html('<%= render 'shared/errors', resource: @answer %>');

<% unless @answer.errors.present? %>
  $("#answer-<%= @answer.id %>").remove()
<% end %>

app/views/answers/update.js.erb
$(".answer-errors").html('<%= render 'shared/errors', resource: @answer %>');

<% unless @answer.errors.present?%>
  $('.answers').html('<%= j render @question.answers %>');
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | QnaRails
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - if user_signed_in?
      p.nav_user
        |  Welcome, 
        b
          = current_user.email
        | !
        br
        = link_to 'Выйти', destroy_user_session_path, method: :delete
        br
    - else
      p.nav_user
        = link_to 'Вoйти', new_user_session_path
        br
    p.notice
      = notice
    p.alert
      = alert
    = yield

app/views/questions/_question.html.slim
p= question.title
p= question.body
p= question.user.email

td
  p= link_to 'Show', question_path(question)
td
  -if current_user&.author_of?(question)
    p= link_to 'Delete', question_path(question), method: :delete, data: {confirm: "Вы уверены?"}
    td
      p= link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id }
      = form_with model: question, class: 'hidden', local: false, html: { id: "edit-question-#{question.id }"} do |f|
        = f.label :title
        = f.text_field :title
        = f.label :body
        = f.text_area :body
        = f.submit 'Save question'
br

app/views/questions/index.html.slim
h2
  | All questions

.questions
  = render @questions
  .question-errors
    = render 'shared/errors', resource: @question
p
  = link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
p
  = render 'shared/errors', resource: @question
= form_with model: @question, local: false do |f|
  p
    = f.label :title
    = f.text_field :title
    = f.label :body
    = f.text_area :body
    = f.submit 'Ask'
  p
    | Author: 
    = current_user.email

td
  = link_to 'Back', questions_path

app/views/questions/show.html.slim
h1= @question.title
p= @question.body

h2
  | Answers

.answers
  =render @question.answers.order(best: :desc)
  .answer-errors
    = render 'shared/errors', resource: @answer

= form_with model: [@question, @answer], class: 'new-answer', local: false do |f|
  = f.label :body, 'Your answer'
  = f.text_area :body
  = f.submit 'Create'

td
  = link_to 'Back', questions_path

app/views/questions/update.js.erb
$(".question-errors").html('<%= render 'shared/errors', resource: @question %>');

<% unless @question.errors.present? %>
  $('.questions').html('<%= j render @question %>');
<% end %>

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b
    = "#{resource.errors.count} error(s) detected: "
  ul
    - resource.errors.full_messages.each do |message|
      li
        = message